sonar.projectKey=home-service-booking-platform
sonar.projectName=Home Service Booking Platform
sonar.projectVersion=1.0

sonar.sources=Backend/booking-service/src/main/java,Backend/provider-service/src/main/java,Backend/notification-service/src/main/java,FrontendDesign/src
sonar.tests=Backend/booking-service/src/test/java,Backend/provider-service/src/test/java,Backend/notification-service/src/test/java
sonar.java.binaries=Backend/booking-service/target/classes,Backend/provider-service/target/classes,Backend/notification-service/target/classes
sonar.java.test.binaries=Backend/booking-service/target/test-classes,Backend/provider-service/target/test-classes,Backend/notification-service/target/test-classes
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/*.min.js,FrontendDesign/src/services/mockDb.js
sonar.test.exclusions=**/target/**
